#!/bin/bash

IMAGE=/tmp/i3lock.png
LOCK_IMAGE=$HOME/.config/awesome/lock.png
# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x5" # 7.52s
#BLURTYPE="0x2" # 4.39s
#BLURTYPE="5x3" # 3.80s
BLURTYPE="2x8" # 2.90s
#BLURTYPE="2x3" # 2.92s

scrot $IMAGE
# convert $IMAGE -level 0%,100%,0.6 -blur $BLURTYPE -pointsize 26 -fill white -gravity center -annotate +0+200 'Type password to unlock' - | composite -gravity center $LOCK_IMAGE - $IMAGE
convert $IMAGE -scale 10% -scale 1000% - | composite -gravity center $LOCK_IMAGE - $IMAGE
i3lock -p default --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c  -i $IMAGE
rm $IMAGE
